[package]
name = "purs-oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
debug = false
strip = "debuginfo"

[build-dependencies]
lalrpop = "0.19.9"

[dependencies]
lalrpop-util = {version="0.19.9", features=["lexer"]}
log = { version = "0.4.17", features = ["max_level_trace", "release_max_level_debug"] }
num = "0.4.0"
regex = "1"
unicode-general-category = "0.6.0"

derive-new = "0.7.0"
salsa = { git = "https://github.com/zyla/salsa.git", branch = "derive-debug-withdb", package = "salsa-2022" }
dashmap = "6.0.1"
anyhow = "1.0.70"
ordered-float = "3.6.0"
rayon = "1.7.0"
fxhash = "0.2.1"
petgraph = "0.6.4"
pretty = "0.12.3"
clap = { version = "4.5.1", features = ["derive"] }
thiserror = "1.0.59"
walkdir = "2.5.0"

[dev-dependencies]
insta = "1.14.0"
indoc = "1.0"
test-generator = "0.3.0"
pretty_assertions = "1.4.0"
env_logger = "0.10.0"



